spring:
  application:
    name: qa-microservice-test-harness

  datasource:
    url: jdbc:postgresql://localhost:5432/harness
    username: harness
    password: harness

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
